init

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -2,19 +2,19 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.50)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.416 2009/11/12 12:44:19 vruppert Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.437 2010/04/25 07:57:19 vruppert Exp $]])
 AC_CONFIG_HEADER(config.h)
 AC_CONFIG_HEADER(ltdlconf.h)
 
 dnl // Put Bochs version information right here so that it gets substituted
 dnl // into all the right places.
-VERSION="2.4.2"
-VER_STRING="2.4.2"
+VERSION="2.4.5"
+VER_STRING="2.4.5"
 dnl // WIN_VER_STRING format is "a, b, c, d"
 dnl // c should be > 90 for pre-release of next version otherwise patch level
 dnl // d should be 0 for release and 1 for cvs version
-WIN_VER_STRING="2, 4, 2, 0"
-REL_STRING="Build from CVS snapshot on November 12, 2009"
+WIN_VER_STRING="2, 4, 5, 0"
+REL_STRING="Build from CVS snapshot, on April 25, 2010"
 
 changequote(<<, >>)
 changequote([, ])
@@ -554,22 +554,18 @@ AC_ARG_ENABLE(cpu-level,
      3)
        AC_MSG_RESULT(3)
        AC_DEFINE(BX_CPU_LEVEL, 3)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 3)
        ;;
      4)
        AC_MSG_RESULT(4)
        AC_DEFINE(BX_CPU_LEVEL, 4)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 4)
        ;;
      5)
        AC_MSG_RESULT(5)
        AC_DEFINE(BX_CPU_LEVEL, 5)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
        ;;
      6)
        AC_MSG_RESULT(6)
        AC_DEFINE(BX_CPU_LEVEL, 6)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
        ;;
      *)
        echo " "
@@ -582,55 +578,18 @@ AC_ARG_ENABLE(cpu-level,
      echo "ERROR: with >1 processor, use --enable-cpu-level=6"
      exit 1
    fi
+   if test "$use_x86_64" = 1 -a "$enableval" -lt 6; then
+     echo "ERROR: --enable-cpu-level=6 required for x86-64 emulation"
+     exit 1
+   fi
   ],
   [
-    # for multiprocessors or x86-64, cpu level must be 6
-    if test "$use_smp" = 1 -o "$use_x86_64" = 1; then
-      AC_MSG_RESULT(6)
-      AC_DEFINE(BX_CPU_LEVEL, 6)
-      AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
-      bx_cpu_level=6
-    else
-      AC_MSG_RESULT(5)
-      AC_DEFINE(BX_CPU_LEVEL, 5)
-      AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
-      bx_cpu_level=5
-    fi
+    AC_MSG_RESULT(6)
+    AC_DEFINE(BX_CPU_LEVEL, 6)
+    bx_cpu_level=6
   ]
   )
 
-
-AC_MSG_CHECKING(for APIC support)
-AC_ARG_ENABLE(apic,
-  [  --enable-apic                     enable APIC support],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_APIC, 1)
-    IOAPIC_OBJS='ioapic.o'
-   else
-    AC_MSG_RESULT(no)
-    if test "$use_smp" = 1; then
-      echo "ERROR: With SMP configuration you must use --enable-apic"
-      exit 1
-    fi
-    AC_DEFINE(BX_SUPPORT_APIC, 0)
-    IOAPIC_OBJS=''
-   fi
-   ],
-  [
-    if test "$use_smp" = 1 -o "$bx_cpu_level" -gt 5; then
-      # enable APIC by default, if SMP configuration or if cpulevel>5
-      AC_MSG_RESULT(yes)
-      AC_DEFINE(BX_SUPPORT_APIC, 1)
-      IOAPIC_OBJS='ioapic.o'
-    else
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_SUPPORT_APIC, 0)
-      IOAPIC_OBJS=''
-     fi
-   ]
-  )
-AC_SUBST(IOAPIC_OBJS)
 
 AC_CHECK_HEADER(zlib.h, [AC_CHECK_LIB(z, gzopen, AC_DEFINE(BX_HAVE_ZLIB,1))] )
 
@@ -812,7 +771,7 @@ AC_ARG_ENABLE(usb-ohci,
   )
 
 if test "$use_usb" = 1; then
-  USBDEV_OBJS="usb_common.o usb_hid.o usb_hub.o usb_msd.o"
+  USBDEV_OBJS="usb_common.o usb_hid.o usb_hub.o usb_msd.o usb_printer.o"
   SCSI_OBJS="scsi_device.o"
   AC_SUBST(USBDEV_OBJS)
   AC_SUBST(SCSI_OBJS)
@@ -901,28 +860,21 @@ fi
 
 AC_SUBST(NETLOW_OBJS)
 
-AC_MSG_CHECKING(for long mode 1G pages support)
-AC_ARG_ENABLE(1g-pages,
-  [  --enable-1g-pages                 support for 1G pages in long mode],
+AC_MSG_CHECKING(for X2APIC support)
+AC_ARG_ENABLE(x2apic,
+  [  --enable-x2apic                   support for X2APIC],
   [if test "$enableval" = yes; then
     AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_1G_PAGES, 1)
-    support_1g_pages=1
+    AC_DEFINE(BX_SUPPORT_X2APIC, 1)
    else
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_1G_PAGES, 0)
-    support_1g_pages=0
+    AC_DEFINE(BX_SUPPORT_X2APIC, 0)
    fi],
   [
     AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_1G_PAGES, 0)
-    support_1g_pages=0
+    AC_DEFINE(BX_SUPPORT_X2APIC, 0)
     ]
   )
-
-if test "$support_1g_pages" = 1 -a "$use_x86_64" = 0; then
-  AC_MSG_ERROR([x86-64 mode is required for 1G pages support])
-fi
 
 AC_MSG_CHECKING(for repeated IO and mem copy speedups)
 AC_ARG_ENABLE(repeat-speedups,
@@ -1011,22 +963,6 @@ AC_ARG_ENABLE(configurable-msrs,
       AC_MSG_RESULT(no)
       AC_DEFINE(BX_CONFIGURE_MSRS, 0)
     fi
-    ]
-  )
-
-AC_MSG_CHECKING(whether to ignore bad MSR references)
-AC_ARG_ENABLE(ignore-bad-msr,
-  [  --enable-ignore-bad-msr           ignore bad MSR references],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_IGNORE_BAD_MSR, 1)
-   else
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_IGNORE_BAD_MSR, 0)
-   fi],
-  [
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_IGNORE_BAD_MSR, 1)
     ]
   )
 
@@ -1445,16 +1381,31 @@ AC_ARG_ENABLE(fpu,
   )
 AC_SUBST(FPU_VAR)
 
+support_vmx=0
 AC_MSG_CHECKING(for VMX support)
 AC_ARG_ENABLE(vmx,
-  [  --enable-vmx                      virtualization extensions],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_VMX, 1)
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_VMX, 0)
-   fi
+  [  --enable-vmx                      VMX (virtualization extensions) emulation (--enable-vmx=[no|1|2])],
+  [case "$enableval" in
+    no | 0)
+      support_vmx=0
+      AC_MSG_RESULT(no)
+      AC_DEFINE(BX_SUPPORT_VMX, 0)
+      ;;
+    yes | 1)
+      support_vmx=1
+      AC_MSG_RESULT(1)
+      AC_DEFINE(BX_SUPPORT_VMX, 1)
+      ;;
+    2)
+      support_vmx=2
+      AC_MSG_RESULT(2)
+      AC_DEFINE(BX_SUPPORT_VMX, 2)
+      ;;
+    *)
+      echo "ERROR: --enable-vmx=$enableval not understood. Use --enable-vmx=[no|1|2]"
+      exit 1
+      ;;
+   esac
    ],
   [
     AC_MSG_RESULT(no)
@@ -1462,29 +1413,13 @@ AC_ARG_ENABLE(vmx,
   ]
   )
 
-support_mmx=1
-AC_MSG_CHECKING(for MMX support)
-AC_ARG_ENABLE(mmx,
-  [  --enable-mmx                      MMX support],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_MMX, 1)
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_MMX, 0)
-    support_mmx=0
-   fi
-   ],
-  [
-    if test "$bx_cpu_level" -ge 5; then
-      AC_MSG_RESULT(yes)
-      AC_DEFINE(BX_SUPPORT_MMX, 1)
-    else
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_SUPPORT_MMX, 0)
-    fi
-    ]
-  )
+if test "$support_vmx" -gt 0 -a "$bx_cpu_level" -lt 6; then
+  AC_MSG_ERROR([for VMX support the CPU level must be set to 6])
+fi
+
+if test "$support_vmx" -gt 1 -a "$use_x86_64" = 0; then
+  AC_MSG_ERROR([VMXx2 support require x86-64 enabled])
+fi
 
 AC_MSG_CHECKING(for 3DNow! support)
 AC_ARG_ENABLE(3dnow,
@@ -1502,132 +1437,6 @@ AC_ARG_ENABLE(3dnow,
     AC_DEFINE(BX_SUPPORT_3DNOW, 0)
   ]
   )
-
-support_sse=0
-AC_MSG_CHECKING(for SSE support)
-AC_ARG_ENABLE(sse,
-  [  --enable-sse                      SSE support (--enable-sse=[no|1|2|3|4])],
-  [case "$enableval" in
-    no | 0)
-      support_sse=0
-      AC_MSG_RESULT(no)
-      ;;
-    yes | 1)
-      support_sse=1
-      AC_MSG_RESULT(SSE1)
-      ;;
-    2)
-      support_sse=2
-      AC_MSG_RESULT(SSE2)
-      ;;
-    3)
-      support_sse=3
-      AC_MSG_RESULT(SSE3)
-      ;;
-    4)
-      support_sse=4
-      AC_MSG_RESULT(SSE4)
-      ;;
-    *)
-      echo "ERROR: --enable-sse=$enableval not understood. Use --enable-sse=[no|1|2|3|4]"
-      exit 1
-      ;;
-   esac
-   ],
-  [
-    if test "$use_x86_64" = 1; then
-      support_sse=2
-      AC_MSG_RESULT(SSE2)
-    else
-      AC_MSG_RESULT(no)
-    fi
-  ]
-  )
-
-if test "$support_sse" -gt 0 -a "$bx_cpu_level" -lt 6; then
-  AC_MSG_ERROR([for SSE support the CPU level must be set to 6])
-fi
-
-if test "$support_sse" -lt 2 -a "$use_x86_64" = 1; then
-  AC_MSG_ERROR([x86-64 needs SSE2 support])
-fi
-
-if test "$support_sse" = 4; then
-  AC_DEFINE(BX_SUPPORT_SSE,  4)
-elif test "$support_sse" = 3; then
-  AC_DEFINE(BX_SUPPORT_SSE,  3)
-elif test "$support_sse" = 2; then
-  AC_DEFINE(BX_SUPPORT_SSE,  2)
-elif test "$support_sse" = 1; then
-  AC_DEFINE(BX_SUPPORT_SSE,  1)
-else
-  AC_DEFINE(BX_SUPPORT_SSE,  0)
-fi
-
-support_sse_extensions=0
-AC_MSG_CHECKING(for SSE extensions support)
-AC_ARG_ENABLE(sse-extension,
-  [  --enable-sse-extension            support for SSE extensions],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_SSE_EXTENSION, 1)
-    support_sse_extensions=1
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_SSE_EXTENSION, 0)
-   fi
-   ],
-  [
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_SSE_EXTENSION, 0)
-  ]
-  )
-
-use_xsave=0
-AC_MSG_CHECKING(for XSAVE/XRSTOR support)
-AC_ARG_ENABLE(xsave,
-  [  --enable-xsave                    support for XSAVE/XRSTOR extensions],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_XSAVE, 1)
-    use_xsave=1
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_XSAVE, 0)
-   fi
-   ],
-  [
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_XSAVE, 0)
-  ]
-  )
-
-if test "$support_sse" -lt 1 -a "$use_xsave" = 1; then
-  AC_MSG_ERROR([XSAVE requires SSE support!])
-fi
-
-use_aes=0
-AC_MSG_CHECKING(for AES instructions support)
-AC_ARG_ENABLE(aes,
-  [  --enable-aes                      support for AES instructions],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_AES, 1)
-    use_aes=1
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_AES, 0)
-   fi
-   ],
-  [
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_AES, 0)
-  ]
-  )
-
-if test "$support_sse" -lt 1 -a "$use_aes" = 1; then
-  AC_MSG_ERROR([AES requires SSE support!])
-fi
 
 AC_MSG_CHECKING(for alignment check support)
 AC_ARG_ENABLE(alignment-check,
@@ -1666,67 +1475,6 @@ AC_ARG_ENABLE(misaligned-sse,
     AC_MSG_RESULT(no)
     AC_DEFINE(BX_SUPPORT_MISALIGNED_SSE, 0)
     ]
-  )
-
-AC_MSG_CHECKING(for SEP support)
-AC_ARG_ENABLE(sep,
-  [  --enable-sep                      SYSENTER/SYSEXIT support],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_SEP, 1)
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_SEP, 0)
-   fi
-   ],
-  [
-    if test "$bx_cpu_level" -ge 6 -a "$support_mmx" = 1; then
-      AC_MSG_RESULT(yes)
-      AC_DEFINE(BX_SUPPORT_SEP, 1)
-    else
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_SUPPORT_SEP, 0)
-    fi
-    ]
-  )
-
-AC_MSG_CHECKING(for POPCNT instruction support)
-AC_ARG_ENABLE(popcnt,
-  [  --enable-popcnt                   support for POPCNT instruction],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_POPCNT, 1)
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_POPCNT, 0)
-   fi
-   ],
-  [
-    if test "$support_sse" -ge 4 -a "$support_sse_extensions" = 1; then
-      AC_MSG_RESULT(yes)
-      AC_DEFINE(BX_SUPPORT_POPCNT, 1)
-    else
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_SUPPORT_POPCNT, 0)
-    fi
-    ]
-  )
-
-AC_MSG_CHECKING(for MOVBE instruction support)
-AC_ARG_ENABLE(movbe,
-  [  --enable-movbe                    support for MOVBE Intel Atom(R) instruction],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_MOVBE, 1)
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_MOVBE, 0)
-   fi
-   ],
-  [
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_MOVBE, 0)
-  ]
   )
 
 AC_MSG_CHECKING(for MONITOR/MWAIT instructions support (experimental))
@@ -1988,7 +1736,7 @@ AC_ARG_ENABLE(iodebug,
    fi
    ],
   [
-    if test "" = 1; then
+    if test "$bx_debugger" = 1; then
       # enable by default if debugger is on
       AC_MSG_RESULT(yes)
       AC_DEFINE(BX_SUPPORT_IODEBUG, 1)
@@ -2848,6 +2596,116 @@ fi
 
 dnl // DEPRECATED configure options - force users to remove them
 
+AC_MSG_CHECKING(for MMX support (deprecated))
+AC_ARG_ENABLE(mmx,
+  [  --enable-mmx                      support for MMX intructions (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to .bochsrc options])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for SSE support (deprecated))
+AC_ARG_ENABLE(sse,
+  [  --enable-sse                      support for SSE intruction set (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to .bochsrc options])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for SSE extensions support (deprecated))
+AC_ARG_ENABLE(sse-extension,
+  [  --enable-sse-extension            support for SSE extensions (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to .bochsrc options])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for POPCNT support (deprecated))
+AC_ARG_ENABLE(popcnt,
+  [  --enable-popcnt                   support for POPCNT intruction (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - enabled automatically if SSE4_2 is enabled])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for MOVBE support (deprecated))
+AC_ARG_ENABLE(movbe,
+  [  --enable-movbe                    support for MOVBE intruction (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to .bochsrc options])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for AES support (deprecated))
+AC_ARG_ENABLE(aes,
+  [  --enable-aes                      support for AES intruction set (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to .bochsrc options])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for XSAVE support (deprecated))
+AC_ARG_ENABLE(xsave,
+  [  --enable-xsave                    support for XSAVE extensions (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to .bochsrc options])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for SEP support (deprecated))
+AC_ARG_ENABLE(sep,
+  [  --enable-sep                      support for SYSENTER/SYSEXIT intructions (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to .bochsrc options])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for APIC support (deprecated))
+AC_ARG_ENABLE(apic,
+  [  --enable-apic                     enable APIC support (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - enabled automatically with SMP or when CPU_LEVEL >= 5])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(whether to ignore bad MSR references (deprecated))
+AC_ARG_ENABLE(ignore-bad-msr,
+  [  --enable-ignore-bad-msr           ignore bad MSR references (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to runtime option in .bochsrc])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
+AC_MSG_CHECKING(for long mode 1G pages support)
+AC_ARG_ENABLE(1g-pages,
+  [  --enable-1g-pages                 support for 1G pages in long mode (deprecated)],
+  [AC_MSG_RESULT($enableval)
+   AC_MSG_ERROR([DEPRECATED - moved to runtime option in .bochsrc])
+  ],
+  [
+   AC_MSG_RESULT(no)
+  ])
+
 AC_MSG_CHECKING(for PAE support (deprecated))
 AC_ARG_ENABLE(pae,
   [  --enable-pae                      enables PAE support (deprecated)],
@@ -2867,6 +2725,7 @@ AC_ARG_ENABLE(mtrr,
   [
    AC_MSG_RESULT(no)
   ])
+
 
 AC_MSG_CHECKING(for LARGE PAGES (PSE) support (deprecated))
 AC_ARG_ENABLE(large-pages,
@@ -2903,36 +2762,6 @@ AC_ARG_ENABLE(vme,
   [  --enable-vme                      virtual 8086 mode extensions (deprecated)],
   [AC_MSG_RESULT($enableval)
    AC_MSG_ERROR([DEPRECATED - enabled automatically for CPU_LEVEL >= 5])
-  ],
-  [
-   AC_MSG_RESULT(no)
-  ])
-
-AC_MSG_CHECKING(for guest to host TLB support (deprecated))
-AC_ARG_ENABLE(guest2host-tlb,
-  [  --enable-guest2host-tlb           enables guest to host addr TLB for speed (deprecated)],
-  [AC_MSG_RESULT($enableval)
-   AC_MSG_ERROR([DEPRECATED - ALWAYS ON])
-  ],
-  [
-   AC_MSG_RESULT(no)
-  ])
-
-AC_MSG_CHECKING(for instruction cache support (deprecated))
-AC_ARG_ENABLE(icache,
-  [  --enable-icache                   support instruction cache (deprecated)],
-  [AC_MSG_RESULT($enableval)
-   AC_MSG_ERROR([DEPRECATED - ALWAYS ON])
-  ],
-  [
-   AC_MSG_RESULT(no)
-  ])
-
-AC_MSG_CHECKING(writes to port e9 go to console (deprecated))
-AC_ARG_ENABLE(port-e9-hack,
-  [  --enable-port-e9-hack             writes to port e9 go to console (deprecated)],
-  [AC_MSG_RESULT($enableval)
-   AC_MSG_ERROR([DEPRECATED - PORT_E9_HACK could be configured through .bochsrc])
   ],
   [
    AC_MSG_RESULT(no)
