init

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -25,6 +25,7 @@ AC_CHECK_SIZEOF(int *)
 AC_CHECK_FUNCS(select, AC_DEFINE(BX_HAVE_SELECT))
 AC_CHECK_FUNCS(snprintf, AC_DEFINE(BX_HAVE_SNPRINTF))
 AC_CHECK_FUNCS(strtoull, AC_DEFINE(BX_HAVE_STRTOULL))
+AC_CHECK_FUNCS(strtouq, AC_DEFINE(BX_HAVE_STRTOUQ))
 AC_CHECK_FUNCS(strdup, AC_DEFINE(BX_HAVE_STRDUP))
 
 AC_MSG_CHECKING(if compiler allows empty structs)
@@ -51,6 +52,52 @@ AC_TRY_COMPILE([#include <hash_map.h>], [],
      AC_MSG_RESULT(yes)
      AC_DEFINE(BX_HAVE_HASH_MAP)
    ], AC_MSG_RESULT(no))
+AC_LANG_RESTORE
+
+AC_MSG_CHECKING(for number of processors)
+AC_ARG_ENABLE(processors,
+  [  --enable-processors                select number of processors (1,2,4)],
+  [case "$enableval" in
+     1)
+       AC_MSG_RESULT(1)
+       AC_DEFINE(BX_SMP_PROCESSORS, 1)
+       AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+       AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 1)
+       ;;
+     2)
+       AC_MSG_RESULT(2)
+       AC_DEFINE(BX_SMP_PROCESSORS, 2)
+       AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+       AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 2)
+       AC_DEFINE(BX_USE_CPU_SMF, 0)
+       ;;
+     4)
+       AC_MSG_RESULT(4)
+       AC_DEFINE(BX_SMP_PROCESSORS, 4)
+       AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 2)
+       AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 4)
+       AC_DEFINE(BX_USE_CPU_SMF, 0)
+       ;;
+     *)
+       echo " "
+       echo "WARNING: processors != [1,2,4] can work, but you need to modify rombios.c manually"
+       AC_MSG_RESULT($enable_val)
+       AC_DEFINE(BX_SMP_PROCESSORS, $enable_val)
+       AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+       AC_DEFINE(BX_IOAPIC_DEFAULT_ID, $enable_val)
+       AC_DEFINE(BX_USE_CPU_SMF, 0)
+       ;;
+   esac
+   bx_procs="$enableval"
+  ],
+  [
+     AC_MSG_RESULT(1)
+     AC_DEFINE(BX_SMP_PROCESSORS, 1)
+     AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+     AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 1)
+     bx_procs=1
+  ]
+  )
 
 AC_MSG_CHECKING(if compiler allows blank labels)
 AC_TRY_COMPILE([], [ { label1: } ],
@@ -59,7 +106,6 @@ AC_TRY_COMPILE([], [ { label1: } ],
       AC_MSG_RESULT(no)
       AC_DEFINE(BX_NO_BLANK_LABELS)
     ])
-AC_LANG_RESTORE
 
 AC_MSG_CHECKING(if compiler allows LL for 64-bit constants)
 AC_TRY_COMPILE([], [ { 42LL; } ],
@@ -68,11 +114,10 @@ AC_TRY_COMPILE([], [ { 42LL; } ],
       AC_MSG_RESULT(no)
       AC_DEFINE(BX_64BIT_CONSTANTS_USE_LL, 0)
     ])
-AC_LANG_RESTORE
 
 AC_MSG_CHECKING(for cpu level)
 AC_ARG_ENABLE(cpu-level,
-  [  --enable-cpu-level                select cpu level (3,4,5)],
+  [  --enable-cpu-level                select cpu level (3,4,5,6)],
   [case "$enableval" in
      3)
        AC_MSG_RESULT(3)
@@ -89,17 +134,36 @@ AC_ARG_ENABLE(cpu-level,
        AC_DEFINE(BX_CPU_LEVEL, 5)
        AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
        ;;
+     6)
+       AC_MSG_RESULT(6)
+       AC_DEFINE(BX_CPU_LEVEL, 6)
+       AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
+       ;;
      *)
        echo " "
        echo "ERROR: you must supply a valid CPU level to --enable-cpu-level"
        exit 1
        ;;
    esac
+   bx_cpu_level=$enableval
+   if test "$bx_procs" -gt 1 -a "$enableval" -lt 6; then
+     echo "ERROR: with >1 processor, use --enable-cpu-level=6"
+     exit 1
+   fi
   ],
   [
-   AC_MSG_RESULT(5)
-   AC_DEFINE(BX_CPU_LEVEL, 5)
-   AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
+    # for multiprocessors, cpu level must be 6
+    if test "$bx_procs" -gt 1; then
+      AC_MSG_RESULT(6)
+      AC_DEFINE(BX_CPU_LEVEL, 6)
+      AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
+      bx_cpu_level=6
+    else
+      AC_MSG_RESULT(5)
+      AC_DEFINE(BX_CPU_LEVEL, 5)
+      AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
+      bx_cpu_level=5
+    fi
   ]
   )
 
@@ -157,13 +221,69 @@ AC_SUBST(DYNAMIC_VAR)
 AC_SUBST(AS_DYNAMIC_OBJS)
 AC_SUBST(AS_DYNAMIC_INCS)
 
+AC_MSG_CHECKING(for APIC support)
+AC_ARG_ENABLE(apic,
+  [  --enable-apic                   enable APIC support],
+  [if test "$enableval" = yes; then
+    AC_MSG_RESULT(yes)
+    AC_DEFINE(BX_APIC_SUPPORT, 1)
+    IOAPIC_OBJS='ioapic.o'
+    APIC_OBJS='apic.o'
+   else
+    AC_MSG_RESULT(no)
+    if test "$bx_procs" -gt 1; then
+      echo "Number of processors = $bx_procs"
+      echo "ERROR: With processors > 1 you must use --enable-apic"
+      exit 1
+    fi
+    AC_DEFINE(BX_APIC_SUPPORT, 0)
+    IOAPIC_OBJS=''
+    APIC_OBJS=''
+   fi
+   ],
+  [
+    if test "$bx_procs" -gt 1 -o "$bx_cpu_level" -gt 5; then
+      # enable APIC by default, if processors>1 or if cpulevel>5
+      AC_MSG_RESULT(yes)
+      AC_DEFINE(BX_APIC_SUPPORT, 1)
+      IOAPIC_OBJS='ioapic.o'
+      APIC_OBJS='apic.o'
+    else
+      AC_MSG_RESULT(no)
+      AC_DEFINE(BX_APIC_SUPPORT, 0)
+      IOAPIC_OBJS=''
+      APIC_OBJS=''
+     fi
+   ]
+  )
+AC_SUBST(IOAPIC_OBJS)
+AC_SUBST(APIC_OBJS)
+
+AC_MSG_CHECKING(for split hard disk image support)
+AC_ARG_ENABLE(split-hd,
+  [  --enable-split-hd                   allows split hard disk image],
+  [if test "$enableval" = yes; then
+    AC_MSG_RESULT(yes)
+    AC_DEFINE(BX_SPLIT_HD_SUPPORT, 1)
+   else
+    AC_MSG_RESULT(no)
+    AC_DEFINE(BX_SPLIT_HD_SUPPORT, 0)
+   fi],
+  [
+    AC_MSG_RESULT(yes)
+    AC_DEFINE(BX_SPLIT_HD_SUPPORT, 1)
+    ]
+  )
+AC_SUBST(BX_SPLIT_HD_SUPPORT)
+
 AC_MSG_CHECKING(for NE2000 support)
 AC_ARG_ENABLE(ne2000,
   [  --enable-ne2000                   enable limited ne2000 support],
   [if test "$enableval" = yes; then
     AC_MSG_RESULT(yes)
     AC_DEFINE(BX_NE2K_SUPPORT, 1)
-    NE2K_OBJS='ne2k.o eth.o eth_fbsd.o eth_null.o'
+    NE2K_OBJS='ne2k.o eth.o eth_null.o'
+    AC_CHECK_HEADER(net/bpf.h, NE2K_OBJS="$NE2K_OBJS eth_fbsd.o")
    else
     AC_MSG_RESULT(no)
     AC_DEFINE(BX_NE2K_SUPPORT, 0)
@@ -307,6 +427,23 @@ AC_ARG_ENABLE(disasm,
   )
 AC_SUBST(DISASM_VAR)
 
+AC_CHECK_LIB(readline, 
+  readline,
+  [
+    if test "$bx_debugger" = 1; then
+      # only add readline library if debugger is on
+      AC_DEFINE(HAVE_LIBREADLINE, 1)
+      READLINE_LIB='-lreadline'
+    fi
+  ]
+)
+  AC_SUBST(READLINE_LIB)
+
+AC_CHECK_HEADER(readline/history.h,
+  AC_DEFINE(HAVE_READLINE_HISTORY_H)
+  )
+
+
 AC_MSG_CHECKING(for loader support)
 AC_ARG_ENABLE(loader,
   [  --enable-loader                   support calling external loader from debugger],
@@ -438,7 +575,8 @@ AC_ARG_ENABLE(fpu,
     echo " "
     echo "ERROR: --enable-fpu does not accept a path"
     exit 1
-   fi],
+   fi
+   ],
   [
     AC_MSG_RESULT(yes)
     AC_DEFINE(BX_SUPPORT_FPU, 1)
@@ -601,12 +739,24 @@ AC_ARG_WITH(nogui,
   [  --with-nogui                      no native GUI, just use blank stubs],
   )
 
+AC_ARG_WITH(term,
+  [  --with-term                       textmode terminal environment],
+  )
+
+AC_ARG_WITH(rfb,
+  [  --with-rfb                        use RFB protocol, works with VNC viewer],
+  )
+
+AC_MSG_CHECKING(for gui library to use)
+
 dnl // make sure X Windows is default if no other chosen
 if (test "$with_x11" != yes) && \
    (test "$with_beos" != yes) && \
    (test "$with_win32" != yes) && \
    (test "$with_nogui" != yes) && \
    (test "$with_win32_vcpp" != yes) && \
+   (test "$with_term" != yes) && \
+   (test "$with_rfb" != yes) && \
    (test "$with_macos" != yes); then
   with_x11=yes
 fi
@@ -633,25 +783,40 @@ CD_UP_ONE="echo done"
 CD_UP_TWO="echo done"
 
 if test "$with_x11" = yes; then
+  AC_MSG_RESULT(X windows)
+  if test "$no_x" = yes; then
+    echo ERROR: X windows gui was selected, but X windows libraries were not found.
+    exit 1
+  fi
   AC_DEFINE(BX_WITH_X11, 1)
   GUI_OBJS='$(GUI_OBJS_X11)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_X)'
 elif test "$with_win32" = yes; then
+  AC_MSG_RESULT(win32)
   AC_DEFINE(BX_WITH_WIN32, 1)
   GUI_OBJS='$(GUI_OBJS_WIN32)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_WIN32)'
 elif test "$with_beos" = yes; then
+  AC_MSG_RESULT(beos)
   AC_DEFINE(BX_WITH_BEOS, 1)
   GUI_OBJS='$(GUI_OBJS_BEOS)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_BEOS)'
+elif test "$with_rfb" = yes; then
+  AC_MSG_RESULT(rfb)
+  AC_DEFINE(BX_WITH_RFB, 1)
+  GUI_OBJS='$(GUI_OBJS_RFB)'
+  GUI_LINK_OPTS='$(GUI_LINK_OPTS_RFB)'
 elif test "$with_win32_vcpp" = yes; then
+  AC_MSG_RESULT(win32-vcpp)
   AC_DEFINE(BX_WITH_WIN32, 1)
   GUI_OBJS='$(GUI_OBJS_WIN32)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_WIN32_VCPP)'
 
   CC="cl"
-  CFLAGS="/nologo /G6 /MT /W3 /GX /O2 /DNDEBUG /DWIN32 /D_WINDOWS"
   CXX="$CC"
+  #C_OPT="/Zi"   # for debugging
+  C_OPT="/O2"   # optimize for speed
+  CFLAGS="/nologo /G6 /MT /W3 /GX /DNDEBUG /DWIN32 /D_WINDOWS $C_OPT"
   CXXFLAGS="$CFLAGS"
   DASH="/"
   SLASH="\\"
@@ -661,7 +826,9 @@ elif test "$with_win32_vcpp" = yes; then
   MAKELIB="lib.exe /nologo /subsystem:console /machine:I386 /verbose /out:\$@"
   RMCOMMAND="-del"
   RANLIB="echo"
-  LINK="link /nologo /subsystem:console /incremental:no /machine:I386 /out:\$@ BINMODE.OBJ"
+  #L_OPT="/debug"    # for debugging
+  L_OPT=""           # no debug info
+  LINK="link $L_OPT /nologo /subsystem:console /incremental:no /machine:I386 /out:\$@ BINMODE.OBJ"
   EXE=".exe"
   PRIMARY_TARGET="bochs.exe"
   COMMAND_SEPARATOR=""
@@ -673,17 +840,66 @@ elif test "$with_win32_vcpp" = yes; then
   AC_DEFINE(BX_NO_ATTRIBUTES, 1)
   AC_DEFINE(BX_HAVE_HASH_MAP, 0)
 elif test "$with_macos" = yes; then
+  AC_MSG_RESULT(macos)
   AC_DEFINE(BX_WITH_MACOS, 1)
   AC_DEFINE(BX_HAVE_STRDUP, 0)
   GUI_OBJS='$(GUI_OBJS_MACOS)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_MACOS)'
+elif test "$with_term" = yes; then
+  AC_MSG_RESULT(term)
+  AC_DEFINE(BX_WITH_TERM, 1)
+  GUI_OBJS='$(GUI_OBJS_TERM)'
+  GUI_LINK_OPTS='$(GUI_LINK_OPTS_TERM)'
+  use_curses=yes
 else
+  AC_MSG_RESULT(none)
   AC_DEFINE(BX_WITH_NOGUI, 1)
   GUI_OBJS='$(GUI_OBJS_NOGUI)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_NOGUI)'
 fi
+
+if test "$use_curses" = yes; then
+  AC_CHECK_LIB(curses, mvaddch, GUI_LINK_OPTS_TERM='-lcurses')
+  AC_CHECK_LIB(ncurses, mvaddch, GUI_LINK_OPTS_TERM='-lncurses')
+  AC_CHECK_LIB(termlib, mvaddch, GUI_LINK_OPTS_TERM='-ltermlib')
+  if test "$GUI_LINK_OPTS_TERM" = ""; then
+    echo Curses library not found: tried curses, ncurses, and termlib.
+    exit 1
+  fi
+fi
+
+if test "$with_rfb" = yes; then
+  # first see if compiler takes "-pthread" argument
+  AC_MSG_CHECKING(for -pthread arg to compiler)
+  CFLAGS_SAVE="$CFLAGS"
+  CFLAGS="$CFLAGS -pthread"
+  AC_TRY_LINK([ #include <pthread.h> ],
+    [ pthread_create(0,0,0,0); ], 
+    [ 
+      # it compiles with -pthread
+      AC_MSG_RESULT(yes) 
+      CXXFLAGS="$CXXFLAGS -pthread"
+    ],
+    [
+      AC_MSG_RESULT(no)
+      # now try with -lpthread
+      CFLAGS="$CFLAGS_SAVE"
+      AC_CHECK_LIB(pthread, 
+	pthread_create,
+	[
+	  # it compiles with -lpthread
+	  RFB_LIBS='-lpthread'
+	],
+	[
+	    echo ERROR: --with-rfb requires the pthread library, which could not be found.; exit 1
+	])
+    ])
+fi
+
+AC_SUBST(RFB_LIBS)
 AC_SUBST(GUI_OBJS)
 AC_SUBST(GUI_LINK_OPTS)
+AC_SUBST(GUI_LINK_OPTS_TERM)
 AC_SUBST(DASH)
 AC_SUBST(SLASH)
 AC_SUBST(CXXFP)
@@ -698,6 +914,8 @@ AC_SUBST(COMMAND_SEPARATOR)
 AC_SUBST(CD_UP_ONE)
 AC_SUBST(CD_UP_TWO)
 
+AC_PATH_PROG(GZIP, gzip)
+AC_PATH_PROG(TAR, tar)
 
 AC_OUTPUT(Makefile iodev/Makefile debug/Makefile bios/Makefile \
          cpu/Makefile memory/Makefile gui/Makefile disasm/Makefile \
